apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/mx-flask-api:latest
          resources: 
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: flask-api-data
              mountPath: /data
      volumes:
        - name: flask-api-data
          persistentVolumeClaim:
            claimName: flask-api-pvc
